# Generated by Django 4.2.3 on 2023-07-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
