# Generated by Django 4.2.3 on 2023-07-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
